export const NotificationTypes = {
  SERVICE_REQUEST_CREATED: "SERVICE_REQUEST_CREATED",
  SERVICE_REQUEST_ESCALATED: "SERVICE_REQUEST_ESCALATED",
  ORDER_READY: "ORDER_READY",
  MENU_ITEM_UNAVAILABLE: "MENU_ITEM_UNAVAILABLE",
  MENU_ITEM_AVAILABLE: "MENU_ITEM_AVAILABLE",
  BILL_GENERATED: "BILL_GENERATED",
  BILL_CLOSED: "BILL_CLOSED",
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  BILL_PAID: "BILL_PAID",
} as const;
