import { PERMISSIONS } from "./permission-keys";

export const ROLE_DEFAULTS = {
  Owner: Object.values(PERMISSIONS),

  Manager: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_UPDATE,
    PERMISSIONS.TABLE_STATUS_UPDATE,
    PERMISSIONS.TABLE_ASSIGN_SERVER,
    PERMISSIONS.TABLE_SESSION_OPEN,
    PERMISSIONS.TABLE_SESSION_CLOSE,

    PERMISSIONS.MENU_VIEW,
    PERMISSIONS.MENU_CATEGORY_CREATE,
    PERMISSIONS.MENU_CATEGORY_UPDATE,
    PERMISSIONS.MENU_ITEM_CREATE,
    PERMISSIONS.MENU_ITEM_UPDATE,
    PERMISSIONS.MENU_ITEM_PRICE_UPDATE,
    PERMISSIONS.MENU_ITEM_AVAILABILITY_UPDATE,
    PERMISSIONS.MENU_MODIFIER_MANAGE,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_NOTE_UPDATE,
    PERMISSIONS.ORDER_ITEM_ADD,
    PERMISSIONS.ORDER_ITEM_REMOVE,
    PERMISSIONS.ORDER_STATUS_UPDATE,

    PERMISSIONS.SERVICE_REQUEST_VIEW,
    PERMISSIONS.SERVICE_REQUEST_CREATE,
    PERMISSIONS.SERVICE_REQUEST_ACKNOWLEDGE,
    PERMISSIONS.SERVICE_REQUEST_RESOLVE,
    PERMISSIONS.SERVICE_REQUEST_REASSIGN,
    PERMISSIONS.SERVICE_REQUEST_ESCALATE,

    PERMISSIONS.KITCHEN_VIEW_QUEUE,
    PERMISSIONS.KITCHEN_STATUS_UPDATE,
    PERMISSIONS.KITCHEN_ITEM_UNAVAILABLE_FLAG,
    PERMISSIONS.KITCHEN_NOTE_VIEW,

    PERMISSIONS.BILL_VIEW,
    PERMISSIONS.BILL_GENERATE,
    PERMISSIONS.BILL_UPDATE,
    PERMISSIONS.BILL_PRINT,
    PERMISSIONS.BILL_FINAL_RECEIPT_PRINT,
    PERMISSIONS.BILL_REPRINT,
    PERMISSIONS.BILL_CLOSE,
    PERMISSIONS.BILL_VOID_APPROVE,
    PERMISSIONS.BILL_SPLIT,

    PERMISSIONS.DISCOUNT_VIEW,
    PERMISSIONS.DISCOUNT_REQUEST,
    PERMISSIONS.DISCOUNT_APPLY,
    PERMISSIONS.DISCOUNT_APPROVE,
    PERMISSIONS.DISCOUNT_REJECT,
    PERMISSIONS.DISCOUNT_EMPLOYEE_APPROVE,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_CAPTURE,
    PERMISSIONS.PAYMENT_MARK_CASH,
    PERMISSIONS.PAYMENT_MARK_CARD,
    PERMISSIONS.PAYMENT_REFUND_REQUEST,
    PERMISSIONS.PAYMENT_REFUND_APPROVE,

    PERMISSIONS.REPORTS_VIEW_BASIC,
    PERMISSIONS.REPORTS_VIEW_FINANCIAL,
    PERMISSIONS.REPORTS_VIEW_STAFF,
    PERMISSIONS.REPORTS_EXPORT,

    PERMISSIONS.RESTAURANT_VIEW_SETTINGS,
    PERMISSIONS.RESTAURANT_UPDATE_SETTINGS,
    PERMISSIONS.RESTAURANT_MODULE_CONFIGURE,
    PERMISSIONS.RESTAURANT_TAX_CONFIGURE,

    PERMISSIONS.AUDIT_VIEW,
  ],

  Server: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_STATUS_UPDATE,
    PERMISSIONS.TABLE_SESSION_OPEN,

    PERMISSIONS.MENU_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_NOTE_UPDATE,
    PERMISSIONS.ORDER_ITEM_ADD,
    PERMISSIONS.ORDER_ITEM_REMOVE,
    PERMISSIONS.ORDER_STATUS_UPDATE,

    PERMISSIONS.SERVICE_REQUEST_VIEW,
    PERMISSIONS.SERVICE_REQUEST_CREATE,
    PERMISSIONS.SERVICE_REQUEST_ACKNOWLEDGE,
    PERMISSIONS.SERVICE_REQUEST_RESOLVE,

    PERMISSIONS.BILL_VIEW,
    PERMISSIONS.BILL_GENERATE,
    PERMISSIONS.BILL_PRINT,

    PERMISSIONS.DISCOUNT_VIEW,
    PERMISSIONS.DISCOUNT_REQUEST,
    PERMISSIONS.DISCOUNT_EMPLOYEE_REQUEST,
  ],

  Cashier: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.BILL_VIEW,
    PERMISSIONS.BILL_GENERATE,
    PERMISSIONS.BILL_UPDATE,
    PERMISSIONS.BILL_PRINT,
    PERMISSIONS.BILL_FINAL_RECEIPT_PRINT,
    PERMISSIONS.BILL_REPRINT,
    PERMISSIONS.BILL_CLOSE,
    PERMISSIONS.BILL_SPLIT,
    PERMISSIONS.BILL_VOID_REQUEST,

    PERMISSIONS.DISCOUNT_VIEW,
    PERMISSIONS.DISCOUNT_REQUEST,
    PERMISSIONS.DISCOUNT_APPLY,
    PERMISSIONS.DISCOUNT_EMPLOYEE_REQUEST,

    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_CAPTURE,
    PERMISSIONS.PAYMENT_MARK_CASH,
    PERMISSIONS.PAYMENT_MARK_CARD,
    PERMISSIONS.PAYMENT_REFUND_REQUEST,

    PERMISSIONS.REPORTS_VIEW_BASIC,
  ],

  Kitchen: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,

    PERMISSIONS.MENU_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.KITCHEN_VIEW_QUEUE,
    PERMISSIONS.KITCHEN_STATUS_UPDATE,
    PERMISSIONS.KITCHEN_ITEM_UNAVAILABLE_FLAG,
    PERMISSIONS.KITCHEN_PRIORITY_UPDATE,
    PERMISSIONS.KITCHEN_NOTE_VIEW,
  ],

  Admin: [
    PERMISSIONS.AUTH_LOGIN,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DISABLE,

    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.ROLES_CREATE,
    PERMISSIONS.ROLES_UPDATE,
    PERMISSIONS.ROLES_ASSIGN,
    PERMISSIONS.PERMISSIONS_MANAGE,

    PERMISSIONS.TABLE_VIEW,
    PERMISSIONS.TABLE_CREATE,
    PERMISSIONS.TABLE_UPDATE,
    PERMISSIONS.TABLE_DELETE,

    PERMISSIONS.MENU_VIEW,
    PERMISSIONS.MENU_CATEGORY_CREATE,
    PERMISSIONS.MENU_CATEGORY_UPDATE,
    PERMISSIONS.MENU_CATEGORY_DELETE,
    PERMISSIONS.MENU_ITEM_CREATE,
    PERMISSIONS.MENU_ITEM_UPDATE,
    PERMISSIONS.MENU_ITEM_DELETE,
    PERMISSIONS.MENU_MODIFIER_MANAGE,

    PERMISSIONS.QR_CONFIG_VIEW,
    PERMISSIONS.QR_CONFIG_UPDATE,
    PERMISSIONS.QR_ENABLE,
    PERMISSIONS.QR_DISABLE,

    PERMISSIONS.BUTTON_CONFIG_VIEW,
    PERMISSIONS.BUTTON_CONFIG_UPDATE,
    PERMISSIONS.BUTTON_ENABLE,
    PERMISSIONS.BUTTON_DISABLE,

    PERMISSIONS.PRINTER_VIEW,
    PERMISSIONS.PRINTER_CREATE,
    PERMISSIONS.PRINTER_UPDATE,
    PERMISSIONS.PRINTER_DELETE,
    PERMISSIONS.PRINTER_ASSIGN,
    PERMISSIONS.PRINTER_TEST,

    PERMISSIONS.RESTAURANT_VIEW_SETTINGS,
    PERMISSIONS.RESTAURANT_UPDATE_SETTINGS,
    PERMISSIONS.RESTAURANT_MODULE_CONFIGURE,
    PERMISSIONS.RESTAURANT_TAX_CONFIGURE,

    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_EXPORT,
  ],
} as const;
